CC = gcc
CFLAGS = -Wall -Wextra -Werror -pedantic

todo_api_0: 4-main.c
	$(CC) $(CFLAGS) -o todo_api_0 4-main.c

todo_api_1: 5-main.c
	$(CC) $(CFLAGS) -o todo_api_1 5-main.c

todo_api_2: 6-main.c
	$(CC) $(CFLAGS) -o todo_api_2 6-main.c

todo_api_3: 7-main.c
	$(CC) $(CFLAGS) -o todo_api_3 7-main.c

todo_api_4: 8-main.c
	$(CC) $(CFLAGS) -o todo_api_4 8-main.c response.c

todo_api_5: 9-main.c
	$(CC) $(CFLAGS) -o todo_api_5 9-main.c trim.c res.c
