strace_0: strace_0.c
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -g3 strace_0.c -o strace_0

strace_1: strace_1.c
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -g3 strace_1.c -o strace_1

strace_2: strace_2.c
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -g3 strace_2.c -o strace_2

strace_3: strace_3.c
	gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -g3 strace_3.c -o strace_3
