#!/usr/bin/env python3

import sys
import os

def find_and_replace_in_heap(pid, search_string, replace_string):
    try:
        # Read the process's memory maps to find heap addresses
        maps_file = f"/proc/{pid}/maps"
        with open(maps_file, 'r') as f:
            for line in f:
                if "[heap]" in line:
                    addr_range = line.split()[0]
                    addr_start, addr_end = map(lambda x: int(x, 16), addr_range.split("-"))
                    break

        # Read the process's memory from the heap
        mem_file = f"/proc/{pid}/mem"
        with open(mem_file, 'rb+') as f:
            f.seek(addr_start)
            heap_data = f.read(addr_end - addr_start)

            # Find and replace the string in the heap data
            modified_heap = heap_data.replace(search_string.encode(), replace_string.encode())

            # Seek back to the start of the heap and write the modified data
            f.seek(addr_start)
            written = f.write(modified_heap)
        print("[*] {:d} bytes written!".format(written))

    except Exception as e:
        print("[ERROR] String '{:s}' not found in heap.".format(search_string))
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: read_write_heap.py pid search_string replace_string")
        sys.exit(1)

    pid = sys.argv[1]
    search_string = sys.argv[2]
    replace_string = sys.argv[3]

    if not pid.isdigit():
        print("Error: PID must be a number.")
        sys.exit(1)

    find_and_replace_in_heap(int(pid), search_string, replace_string)

